#!/bin/bash

# dib-lint: disable=setu setpipefail
if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -e

cat << END > /etc/hosts
127.0.0.1	$(hostname) localhost
::1		localhost ip6-localhost ip6-loopback
ff02::1		ip6-allnodes
ff02::2		ip6-allrouters
END
