#!/bin/bash

# dib-lint: disable=setu setpipefail
if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -e

# NOTE(jamielennox): This is overly simplistic for now, when we have more image
# types we will need to do a better job of a standard resolv.conf

ln -sf /run/resolvconf/resolv.conf /etc/resolv.conf
