#!/bin/bash

# dib-lint: disable=setu setpipefail
if [ "${DIB_DEBUG_TRACE:-0}" -gt 0 ]; then
    set -x
fi
set -e

# using new dib patch, hopefully shouldn't need this

#rm -f /etc/resolv.conf.ORIG
#ln -s /run/resolvconf/resolv.conf /etc/resolv.conf.ORIG
#
#cat << EOF > /etc/resolv.conf.ORIG
#nameserver 8.8.8.8
#nameserver 8.8.4.4
#EOF
